config/routes.rb
Rails.application.routes.draw do
  resources :budgets
  get 'users/show'
  get 'users/profile'

  resources :posts
  root 'pages#home'

  get 'pages/contact'
  get 'pages/about'
  get 'pages/product'
  get 'pages/calendar'

  devise_for :users

end

app/models/budget.rb
class Budget < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true

  validates :user_id, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  has_many :posts
  has_many :budgets

  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end  

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
  
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_filter :is_owner, only: [:destroy, :edit]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to budgets_path, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:type_event, :place, :date, :service, :stay_contact)
    end

    def is_owner
      set_budget
      if user_signed_in?
        if current_user.username != "admin"
          if @budget.user_id != current_user.id
            redirect_to budgets_url, notice: 'You have no permission to manage this topic.'
          end
        end
      else
        redirect_to budgets_url, notice: 'You have no permission to manage this topic.'      
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def product
  end

  def calendar
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new]
  before_filter :is_owner, only: [:destroy, :edit]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        #format.html { redirect_to @post, notice: 'The topic was successfully created.' }
        format.html { redirect_to posts_url, notice: 'The topic was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        #format.html { redirect_to @post, notice: 'The topic was successfully updated.' }
        format.html { redirect_to posts_url, notice: 'The topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy    
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'The topic was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end

    def is_owner
      set_post
      if user_signed_in?
        if current_user.username != "admin"
          if @post.user_id != current_user.id
            redirect_to posts_url, notice: 'You have no permission to manage this topic.'
          end
        end
      else
        redirect_to posts_url, notice: 'You have no permission to manage this topic.'      
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :is_owner, only: [:show]
  
  def show
  	@user = User.all
  end

  def is_owner
  	if user_signed_in?
    	if current_user.email != "admin@admin.org"
        	redirect_to "/", notice: 'You have no permission to access this page.'      
    	end
    else
    		redirect_to "/", notice: 'You have no permission to access this page.'      
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_form.html.erb
<%= simple_form_for(@budget) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <br></br>
    <%= f.input :type_event, label: 'Type of the event: (ex.: Marriage, Anniversary)' %>
    <%= f.input :place , label: 'Place of the event' %>
    <b>Choose the date of the event</b><br>
    <%= f.date_select :date,{:order => [:day, :month, :year], :start_year => 2015, :end_year => 2020}%>
    <br></br>
    <%= f.input :service , label: 'What services do you want? (Photography / Cinegraphy / Both)'%>
    <%= f.input :stay_contact, label: 'Would you want to stay in contact with the company? (Yes or No)'%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/budgets/edit.html.erb
<div class="page-header">
  <h1>Edit your Budget</h1>
</div>

<%= render 'form' %>

<br>

<%= link_to t('.edit', :default => t("helpers.links.Show")),
                @budget, :class => 'btn btn-default' %>

<%= link_to t('.edit', :default => t("helpers.links.Back")),
                budgets_path, :class => 'btn btn-default' %>

<!--
<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>
-->

app/views/budgets/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>Budgets</h1>
</div>

<% if user_signed_in? %>
  <% if current_user.username != "admin" %>
    <p align="center"><%= link_to t('.new', :default => t("helpers.links.New Budget")),
                new_budget_path,
                :class => 'btn btn-primary' %></p>
  <% else %>
    <p align="center"><%= link_to t('.new', :default => t("helpers.links.New Budget")),
                new_budget_path,
                :class => 'btn btn-primary' %></p>
  <% end %>
<% end %>


<table class="table table-striped">
  <thead>
  <tr>
    <% if !user_signed_in? %>
      <center><h1> :-( </h1>
      <h3> You have no budgets registered right now</h3></center>            
    <% else %>  
      <% if current_user.username == "admin" %>
        <% if !@budgets.blank? %>
          <th><%= model_class.human_attribute_name(:Type) %></th>
          <th><%= model_class.human_attribute_name(:Place) %></th>
          <th><%= model_class.human_attribute_name(:Date_event) %></th>
          <th><%= model_class.human_attribute_name(:Created_at) %></th>
          <th><%= model_class.human_attribute_name(:Service) %></th>
          <th><%= model_class.human_attribute_name(:Stay_in_contact_?) %></th>        
        <% else %>
          <center><h1> :-( </h1>
          <h3> You have no budgets registered right now</h3></center>
        <% end %>
      <% end %>
    <% end %>    
    </tr>
  </thead>
  <tbody>
    <% if !@budgets.blank? %>
      <% if user_signed_in? %>
        <% if current_user.username == "admin" %>    
          <% if @budgets.blank?%>
            <center><h1> :-( </h1>
            <h3> You have no budgets registered right now</h3></center>
          <% else %>
              <% @budgets.each do |budget| %>
              <tr>
                  <td><%= link_to budget.type_event, budget_path(budget) %></td>
                  
                  <td><%= budget.place %></td>
                  
                  <td><%= budget.date.strftime("%m/%d/%Y - %I:%M%P") %></td>  

                  <td><%= budget.created_at.strftime("%m/%d/%Y - %I:%M%P") %></td>                     

                  <td><%= budget.service %></td>

                  <td><%= budget.stay_contact %></td>      
              </tr>
            <% end %>
          <% end %>
      <% end %>
    <% else %>
      <center><h1> :-( </h1>
      <h3> You have no budgets registered right now</h3></center>            
    <% end %>
  <% end %>  
  </tbody>
</table>

app/views/budgets/new.html.erb
<div class="page-header">
  <h1>New Budget</h1>
</div>

<%= render 'form' %>

<br></br>

<%= link_to t('.edit', :default => t("helpers.links.Back")),
                budgets_path, :class => 'btn btn-default' %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type event:</strong>
  <%= @budget.type_event %>
</p>

<p>
  <strong>Place:</strong>
  <%= @budget.place %>
</p>

<p>
  <strong>Date:</strong>
  <%= @budget.date %>
</p>

<p>
  <strong>Service:</strong>
  <%= @budget.service %>
</p>

<p>
  <strong>Stay contact:</strong>
  <%= @budget.stay_contact %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VJ Foto Video" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Services", "/pages/product"  %></li>
            <li><%= link_to "Contact", "/pages/contact"  %></li>

            <% if user_signed_in? %>
              <li><%= link_to "Your Profile", "/users/profile"  %></li>              

              <% if current_user.email == "admin@admin.org" %>
                <li><%= link_to "Show All Users", "/users/show"  %></li>              
              <% end %>
            <% end %>



          </ul>
            <br><p align="right"><% if user_signed_in? %>
              Signed in as <b><%= current_user.username %></b>. Not you?
              <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
            <% else  %>
              <%= link_to 'Sign up', new_user_registration_path  %> or <%= link_to 'Sign in', new_user_session_path  %>
            <% end  %>
            </p>
        </div>
      </div>
    </div>

   <div class="container">
      <div class="row">
	<div class="col-lg-9">
	  <%= bootstrap_flash %>
	  <%= yield %>
	</div>
	<div class="col-lg-3">
	  <div class="well sidebar-nav">
	    <h3><strong>Menu</strong></h3>
	    <ul class="nav nav-list">
	      <li><%= link_to "Discussions", "/posts" %></li>
                <% if user_signed_in? %>       
                  <li><%= link_to "Budget", budgets_path  %></li>
                <% end %>            
              <li><%= link_to "Calendar", "/pages/calendar"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <p align="bottom">
      <footer>
        <p>&copy; Mateus Manuel & Vitor Barbosa</p>
      </footer>
    </p>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

<div class="page-header"> 
	<h1>About</h1> 
</div>

<body>
	<p>The life is marked by moments. However, if we don't take care of small souvenirs, definitely, this can simply get lost int time and memory.To relive those emotions a quality of image, an enchantment of details and a good sense becomes indispensable. And is in this rescue of stories that the VJ Foto Video Company search to provide the best service of photo an film. </p>
</body>

app/views/pages/calendar.html.erb
<div class="page-header">
  <h1>Calendar</h1>
</div>

	<center>
		<p><b><h2>We're working on that!</h2></b></p>
			
		<%= image_tag("/under-construction-icon.png", :alt => "rss feed", :width => 150, :height =>150) %>		
	</center>

<!--<p>Find me in app/views/pages/calendar.html.erb</p>-->

app/views/pages/contact.html.erb
<div>
<address>
	<br><br>
	<h4><strong>VJ Foto Video Company</strong></h4><br>
    	Área Especial de Indústria Projeção A, UNB - DF-480<br>
      	Gama Leste, Brasília - DF, 72444-240<br>
      	
    </address>
     
    <address>
      <strong>Contact: </strong><br>
      <abbr title="Phone">P:</abbr> (061) 3356-2131 <br>
      <a href="mailto:#">vjfotovideo@gmail.com</a>
</address>
</div>

<head>
	<script src="http://maps.googleapis.com/maps/api/js"></script>
	<script>
	function initialize() {
  		var mapProp = {
  		center:new google.maps.LatLng(-15.9881221,-48.0441784),
    	zoom:16,
   		mapTypeId:google.maps.MapTypeId.ROADMAP
  		};
  	var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
	}
	google.maps.event.addDomListener(window, 'load', initialize);
	</script>
</head>

<body>
	<div id="googleMap" style="width:500px;height:380px;"></div>
</body>

app/views/pages/home.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    	<%= image_tag("logo_preen.png")%>
    </div>
    <div class="item">
    	<%= image_tag("slide_1.png")%>
      <div class="carousel-caption">
        <p><b>Cenários Impressionantes...</b></p>
      </div>
    </div>
    <div class="item">
    	<%= image_tag("slide_2.png")%>
      <div class="carousel-caption">
        <p><b>...Belas Histórias...</b></p>
      </div>
    </div>
    <div class="item">
    	<%= image_tag("slide_3.png")%>
      <div class="carousel-caption">
        <p><b>...Lindas Imagens</b></p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="sr-only">Next</span>
  </a>
</div>

<div>
	<p class="text"><h5><br><br>The life is marked by moments. However, if we don't take care of small souvenirs, definitely, this can simply get lost int time and memory.To relive those emotions a quality of image, an enchantment of details and a good sense becomes indispensable. And is in this rescue of stories that the VJ Foto Video Company search to provide the best service of photo an film.</h5></p>
</div>

<center>
<div class="row border">
	<%= image_tag("photo.png")%> <b>Photo</b>
    
<div class="row">
	<%= image_tag("video.png")%> <b>Video</b>
</div>
</center>

app/views/pages/product.html.erb
<h4>The <strong>VJ Photo Video Company</strong> is speciallized mainly at weddings, but that doesn't mean that we fail to provide quality service in other types of events. <br><br></h4> 
	
<div align="center" class="row">
  <div class="col-sm-6 col-md-6">
    <div class="thumbnail">
    <%= image_tag("wedding.png")%> 
      <div class="caption">
        <h3>Wedding</h3>
      </div>
    </div>
  </div>
 </div>

<div align="center" class="row">
  <div class="col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("graduation.png")%>
      <div class="caption">
        <h3>Graduation</h3>
      </div>
    </div>
  </div>
</div>

<div align="center" class="row">
  <div class="col-sm-6 col-md-6">
    <div class="thumbnail">
      <%= image_tag("party.png")%>
      <div class="caption">
        <h3>Children's party</h3>
      </div>
    </div>
  </div>
</div>

<div align="center" class="row">
  <div class="col-sm-6 col-md-6">
    <div class="thumbnail">
     <%= image_tag("fifteen.png")%>
      <div class="caption">
        <h3>Sweet Fifteen Party</h3>
      </div>
    </div>
  </div>
</div>

 

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= error_span(@post[:title]) %>
  <%= f.input :description %>
  <%= error_span(@post[:description]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
	<h1>Discussions</h1>
</div>


<p align="right"><%= link_to t('.new', :default => t("helpers.links.New Topic")),
            new_post_path,
            :class => 'btn btn-primary' %></p>


<table class="table table-striped">
  <thead>
  <tr>
    <% if !@posts.blank? %>
      <th><%= model_class.human_attribute_name(:Title) %></th>
      <th><%= model_class.human_attribute_name(:Description) %></th>
      <th><%= model_class.human_attribute_name(:Date) %></th>
      <th><%= model_class.human_attribute_name(:Owner) %></th>
      
      <% @posts.each do |post| %>
        <% if user_signed_in? %>
            <% if current_user.username == post.user.username %>
              <th><%=t '.actions', :default => t("helpers.Manage") %></th>              
            <% end %>
        <% end %>
      <% end %>
    
    <% else %>
      <center><h1> :-( </h1>
      <h3> There are no discussions going on right now</h3></center>
    <% end %>

    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
     	<tr>
     	 	  <td><%= link_to post.title, post_path(post) %></td>
          
          <td><%= post.description %></td>
   	      
          <td><%= post.created_at.strftime("%m/%d/%Y - %I:%M%P") %></td>      

          <td><%= post.user.username %></td>

       	  <% if user_signed_in? %> 
            <% if current_user.username == post.user.username || current_user.username == "admin"%>  
              <td>
           	    <%= link_to t('.edit', :default => t("helpers.links.edit")),
             	              edit_post_path(post), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                 	          post_path(post),
                   	        :method => :delete,
                      	      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        	    :class => 'btn btn-xs btn-danger' %>
              </td>
            <% end %>
          <% end %>
        
 	    </tr>
  	<% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>New Topic</h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <!--<h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>-->
  <h1><%= @post.title %></h1>
</div>

<dl class="dl-horizontal">
  <!--<dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>-->
  <pre><h3>&nbsp;<%= @post.description %></h3></pre>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>

<% if user_signed_in? %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_post_path(@post), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                post_path(@post),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>

app/views/users/profile.html.erb
<%- model_class = User -%>
<div class="page-header">
	<h1>Your Profile</h1>
</div>

<p align="right"><%= link_to t('.new', :default => t("helpers.links.Edit Profile")),
            edit_user_registration_path,
            :class => 'btn btn-primary' %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:Username) %></th>       
      <th><%= model_class.human_attribute_name(:Email) %></th>       
      <th><%= model_class.human_attribute_name(:Created_At) %></th>       
    </tr>
  </thead>

<tbody>
    <% if user_signed_in? %>
     	<tr>
      	<td><%= current_user.username %></td>
        <td><%= current_user.email %></td>
        <td><%= current_user.created_at.strftime("%m/%d/%Y - %I:%M%P") %></td>
  	  </tr>
  	<% end %>
  </tbody>
</table>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>